// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_render.ts";
import * as $3 from "./routes/api/deleteArticle.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/articles/[id].tsx";
import * as $6 from "./routes/articles/create.tsx";
import * as $7 from "./routes/auth/login.tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/ContentForm.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/DeleteButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_render.ts": $2,
    "./routes/api/deleteArticle.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/articles/[id].tsx": $5,
    "./routes/articles/create.tsx": $6,
    "./routes/auth/login.tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/ContentForm.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/DeleteButton.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
